---
- hosts: kubernetes-worker-nodes
  vars_files:
  - env_variables
  tasks:
  - name: Copying token to worker nodes
    copy: src=/home/tplan/{{ token_file }} dest=/home/tplan/join_token

  - name: Joining worker nodes with kubernetes master
    become: true
    become_user: root
    shell: |
     kubeadm reset -f
     cat /home/tplan/join_token | tail -2 > out.sh
     sh out.sh
