---
- hosts: all
  vars_files:
  - env_variables
  tasks:
  - name: Disabling Swap on all nodes
    shell: sudo swapoff -a

  - name: Commenting Swap entries in /etc/fstab
    become: true
    become_user: root
    replace:
     path: /etc/fstab
     regexp: '(.*swap*)'
     replace: '#\1'

  
